meal_plans/urls.py
from django.urls import path

from meal_plans.views import (
    MealCreateView,
    MealUpdateView,
    MealDeleteView,
    MealDetailView,
    MealListView,
)

urlpatterns = [
    path("", MealListView.as_view(), name="meal_list"),
    path("<int:pk>/", MealDetailView.as_view(), name="meal_detail"),
    path("create/", MealCreateView.as_view(), name="meal_new"),
    path("<int:pk>/edit/", MealUpdateView.as_view(), name="meal_edit"),
    path("<int:pk>/delete/", MealDeleteView.as_view(), name="meal_delete"),
]

scrumptious/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("recipes/", include("recipes.urls")),
    path("meal_plans/", include("meal_plans.urls")),
    path("tags/", include("tags.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("recipes_list")),
        name="home",
    ),
    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),
]

tags/urls.py
from django.urls import path

from tags.views import (
    TagListView,
    TagCreateView,
    TagDetailView,
    TagUpdateView,
    TagDeleteView
)

urlpatterns = [
    path("", TagListView.as_view(), name="tags_list"),
    path("new/", TagCreateView.as_view(), name="tag_new"),
    path("<int:pk>/", TagDetailView.as_view(), name="tag_detail"),
    path("<int:pk>/edit/", TagUpdateView.as_view(), name="tag_edit"),
    path("<int:pk>/delete/", TagDeleteView.as_view(), name="tag_delete"),
]

meal_plans/models.py
from django.conf import settings
from django.db import models


USER_MODEL = settings.AUTH_USER_MODEL


class Meal_Plan(models.Model):
    owner = models.ForeignKey(
        USER_MODEL,
        related_name="meals",
        on_delete=models.CASCADE,
        null=True,
    )
    name = models.CharField(max_length=120)
    description = models.TextField()
    image = models.URLField(null=True, blank=True)
    recipes = models.ManyToManyField("recipes.Recipe", related_name="meals")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    date = models.DateField(
        blank=True,
        null=True,
        editable=True)

    def __str__(self):
        return self.name + " by " + str(self.owner)

meal_plans/views.py
from django.urls import reverse_lazy
from django.shortcuts import redirect
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin
from meal_plans.models import Meal_Plan


class MealCreateView(LoginRequiredMixin, CreateView):
    model = Meal_Plan
    template_name = "meal_plans/new.html"
    fields = ["name", "description", "image", "recipes", "date"]
    success_url = reverse_lazy("meal_list")

    def form_valid(self, form):
        plan = form.save(commit=False)
        plan.owner = self.request.user
        plan.save()
        form.save_m2m()
        return redirect("meal_detail", pk=plan.id)


class MealUpdateView(LoginRequiredMixin, UpdateView):
    model = Meal_Plan
    template_name = "meal_plans/edit.html"
    fields = ["name", "owner", "description", "image", "recipes", "date"]

    def get_success_url(self) -> str:
        return reverse_lazy("meal_detail", args=[self.object.id])


class MealListView(LoginRequiredMixin, ListView):
    model = Meal_Plan
    template_name = "meal_plans/list.html"
    paginate_by = 4

    def get_queryset(self):
        user = self.request.user
        return Meal_Plan.objects.filter(owner=user)


class MealDetailView(DetailView):
    model = Meal_Plan
    template_name = "meal_plans/detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class MealDeleteView(LoginRequiredMixin, DeleteView):
    model = Meal_Plan
    template_name = "meal_plans/delete.html"
    success_url = reverse_lazy("meal_list")

meal_plans/templates/meal_plans/delete.html
{% extends 'base.html' %}

{% block content %}
<main>
  <form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ meal_plan }}"?</p>
    {{ form.as_p }}
    <div class="control">
      <button class="button">Delete</button>
    </div>
  </form>
</main>
{% endblock content %}

meal_plans/templates/meal_plans/detail.html
{% extends 'base.html' %} {% block content %}
<main class="recipe-detail">
  <div>
    <a href="{% url 'meal_edit' meal_plan.id %}">Edit</a>
    <a href="{% url 'meal_delete' meal_plan.id %}">Delete</a>
  </div>
  {% if meal_plan.image %}
  <img src="{{ meal_plan.image }}" class="pull-right" />
  {% endif %}
  <h1>{{ meal_plan.owner | default_if_none:"Unknown" }}'s Meal Plan</h1>
  <h2>{{ meal_plan.name }}</h2>
  <h2>for: {{ meal_plan.date | default_if_none:"Today" }}</h2>
  <br />
  <tbody>
    {% for ingredient in meal_plan.recipes.all %}
    <tr>
      <td>
        -<a href="{% url 'recipe_detail' ingredient.id %}"
          >{{ ingredient.name }}</a
        >
      </td>
      <br />
    </tr>
    {% endfor %}
  </tbody>
  <p>Created on {{ meal_plan.created }} | Updated on {{ meal_plan.updated }}</p>
</main>
{% endblock content %}

meal_plans/templates/meal_plans/edit.html
{% extends 'base.html' %}

{% block content %}
<main class="recipe-form">
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="control">
      <button class="button">Update</button>
    </div>
  </form>
  <a href="{% url 'recipe_new' %}">Create new recipe</a>
</main>
{% endblock content %}

meal_plans/templates/meal_plans/list.html
{% extends 'base.html' %}

{% block content %}
<main class="recipe-grid">
  {% for meal in meal_plan_list %}
  <div class="recipe-card">
    <h2 class="recipe-card-title">
      <a href="{% url 'meal_detail' meal.pk %}">{{ meal.name }}</a>
    </h2>
    <p class="recipe-card-date">{{ meal.updated }}</p>

    {% for ingredient in meal.recipes.all %}
    <p>
      -<a href="{% url 'recipe_detail' ingredient.id %}">{{ ingredient.name }}</a>
    </p>
    {% endfor %}
  </div>
  {% empty %}
  <h2>No Meal Plans</h2>
  {% endfor %}
</main>

{% endblock content %}



{% block pagination %}
<footer>
  <a href="{% url 'meal_new' %}">Create New Meal Plan</a>
  <div class="pagination">
    <span class="step-links">
      {% if page_obj.has_previous %}
      <a href="?page=1">&laquo; first</a>
      <a href="?page={{ page_obj.previous_page_number }}">previous</a>
      {% endif %}

      <span class="current">
        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
      </span>

      {% if page_obj.has_next %}
      <a href="?page={{ page_obj.next_page_number }}">next</a>
      <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
      {% endif %}
    </span>
  </div>
</footer>
{% endblock pagination %}

meal_plans/templates/meal_plans/new.html
{% extends 'base.html' %}

{% block content %}
<main class="recipe-form">
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="control">
      <button class="button">Create</button>
    </div>
  </form>
  <a href="{% url 'recipe_new' %}">Create new recipe</a>
</main>
{% endblock content %}